### PR TITLE
start sleeping

### PR DESCRIPTION
**Pull request by joehand**
basic sleep functionality.

* uses mirror-folder for importing
* Not copying to files yet

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
very :cool:

**Comment by joehand** [comment]
Very close! Currently it transfers everything between sleep files (ram by default) and basic UI is all set. Once mafintosh makes it so the files get downloaded in hyperdrive we can merge & release!

Gonna work on the secret key storage and localcast plugins next.

**Comment by juliangruber** [comment]
so very very exciting <3

**Comment by joehand** [comment]
Outlined a few things I want to tackle in this version of dat-next https://github.com/joehand/dat-next/issues/121 (though will merge/release as soon as file support works).

**Pull request merged**
