### PR TITLE
remove node 4, add node 5 to travis tests

### PR DESCRIPTION
**Pull request by okdistribute**

### CODE REVIEW

**Comment by joehand** [comment]
Whats the motivation for this? Seems like keeping v4 would be good until april: https://github.com/nodejs/LTS

**Comment by okdistribute** [comment]
Tests are failing. Is that something we can fix easily?
We can still say we support 4 even if we remove it from travis, I think

**Comment by joehand** [comment]
🎉 passing now https://travis-ci.org/joehand/dat-next/builds/195367634. The tests in this PR are failing because of those error handling changes.

If we intend to support v4 then it'll be nice to have it in travis. I'd regularly forget to switch versions to run tests locally =).

**Comment by okdistribute** [comment]
cool!

**Pull request closed without merging**
